---
deployment:
  tasks:
    - export DEPLOYPATH=/home/carlosbeltranjvn/public_html/
    - /bin/cp -R  . $DEPLOYPATH
    - /bin/cp -r  .git
    # - /bin/cp -R --exclude='.git' .  $DEPLOYPATH

metadata:
    name: "Politicos"
    version: "1.0"
    author: "Digital Space"
post_deploy:
    # - command: npm run test-api
    # - command: newman run tests/Cinoc.postman_collection.json > report.txt
    # - /usr/local/cpanel/3rdparty/bin/git checkout --theirs .
pre_deploy:
hooks:
  pre:
    # - command: "echo 'Backing up files...'"
  post:
    # - command: npm run test-api
    # - command: newman run tests/Cinoc.postman_collection.json > report.txt
    # - command: "echo 'Deployment complete.'"